### ISSUE TITLE
Level Scaling

### ISSUE THREAD

**Issue by Sparkhon** [MiStchec/TowerDefense#3]
Wir müssen das Levelscaling ändern, sodass sich das Levelimage nicht mehr an die Fenstergröße anpasst, damit ich das Shopfenster platzieren kann und es nicht über dem Level liegt

**Comment by mistecklein** [comment]
Ich pushe heute mal die aktuelle Version rein, funktioniert nur leider noch nicht ganz so sehr. Dort ist aber schon ausgestellt, das man die Größe vom Fenster umstellen kann (aktuell fix 1280x720)
